export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const RETURN_PRODUCT_REQUEST = 'RETURN_PRODUCT_REQUEST'
export const RETURN_PRODUCT_SUCCESS = 'RETURN_PRODUCT_SUCCESS'
export const RETURN_PRODUCT_FAILURE = 'RETURN_PRODUCT_FAILURE'

